#
# This file contains configuration flags to customize your site
#
theme: hacker
# Name of your site (displayed in the header)
name: Terje Sandstrøm

# Short bio or description (displayed in the header)
description: Visual Studio ALM MVP

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/203432?v=3&amp;s=40

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook: terje.sandstrom
  flickr:
  github: osiristerje
  instagram:
  linkedin:  terjesandstrom
  pinterest:
  rss: whatever # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: osiristerje
  stackoverflow: users/1203904/terje-sandstrøm  # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: terjesandstrom.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

relative_permalinks: false

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge

#markdown: redcarpet
#highlighter: pyments

#permalink: /:title/
permalink: none   
# The release of Jekyll Now that you're using
version: v1.1.0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
